name: my first github actions 

on: push

jobs:
  myfirst-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: echo test
        run: echo "hello github actions"
      - name: multi script
        run: |
          node -v
          npm -v
       