name: first action

on: push

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: |
          echo " Hello Github actions"
          pwd
          ls -a
          echo " ${{ toJson(github) }}" 
      