name: first action
run-name: run-name-First action
on: push
jobs:

  commit:
    runs-on: ubuntu-latest
    timeout-minutes: 
    steps:
      - name: step 1
        run: |
          echo " Hello Github actions"
          pwd
          ls -a
          echo " ${{ toJson(github) }}" 
      