name: first action
run-name: run-name-First action
on: push
jobs:

  commit:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: step 1
        run: |
          echo " Hello Github actions"
          pwd
          ls -a
          echo " ${{ toJson(github) }}" 
      - name: Node default version
        run: |
          node -v
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Node version after setup node
        run: |
          node -v     
      